## **Function**


---



---


Function is a block of code which performs certin task when called

syntax:


```
def <function name> (parameters)
```




In [0]:
# defining a function

def multiply(x):
  return x**2

a = int(input("Enter an number"))

# calling the function
print("Square of the number passed by user is:",multiply(a))

Enter an number3
Square of the number passed by user is: 9


## Inbuilt functions

map()

> returns a map object of the results after applying the given function to each item of a given iterable.

lambda()


> it is an samll autonomous function.This function can have any number of arguments but only one expression, which is evaluated and returned.

split()



> this function splits the string passed into an list of characters depending upon the seperator passed


join()

> this function works exactly opposite to the split(), i.e.,joins the list back into a string





In [0]:
a = [1,2,3,4,5,6,7]

f=lambda x:x**2

print(f(3))

square=map(f,a)
print(list(square))

str_r="hello i am programmer"
b=str_r.split(" ")
print(b)

str_o=" ".join(b)
print(str_o)

9
[1, 4, 9, 16, 25, 36, 49]
['hello', 'i', 'am', 'programmer']
hello i am programmer


## **Numpy**


---



---


NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays.

pip command for installing numpy library is

```
pip install numpy
```


In [0]:
import numpy as np

# creating an array
a = np.array([1,3,5,6])
print(a)

[1 3 5 6]


In [0]:
import numpy as np

# creating multidimension array
a = np.array([[2,6,7],[78,6,4,],[7,8,9]])
print(a)

[[ 2  6  7]
 [78  6  4]
 [ 7  8  9]]


In [0]:
import numpy as np

# creating a empty array
a = np.empty([3,3],dtype="int8")
print(a)

# creating an array whose every element is zero
b = np.zeros([2,6])
print(b)

# creating an array whose every element is one
c = np.ones([5,6])
print(c)

[[-80  65 -94]
 [  4   0   0]
 [  0   0  64]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [0]:
# using dtype parameter
import numpy as np

# giving datatype of every element as complex
a = np.array([1,3,5],dtype = "complex")
print(a)

# giving datatype of every element as float
a = np.array([1,3,5],dtype = "float")
print(a)

[1.+0.j 3.+0.j 5.+0.j]
[1. 3. 5.]


In [0]:
# ndarray returns dimension of ndarray
import numpy as np

a = np.array([[1,3,2],[3,6,7]])
print(a.shape)

(2, 3)


In [0]:
import numpy as np

# creating one dimensional array 
# using arange()
# it returns the numbers in the range of specified value
# creates an spaced array
import numpy as np 
a = np.arange(24) 
a.ndim # .ndim returns array dimension
print(a.ndim)

# now reshape it 
b = a.reshape(2,4,3) 
print (b) 
# b is having three dimensions

1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [0]:
import numpy as np
# using some universal functions
a=np.array([[1,4,5],[2,6,8]])

# exponential values 
print ("Exponent of array elements:\n", np.exp(a)) 
  
# square root of array values 
print ("Square root of array elements:\n", np.sqrt(a)) 


Exponent of array elements:
 [[2.71828183e+00 5.45981500e+01 1.48413159e+02]
 [7.38905610e+00 4.03428793e+02 2.98095799e+03]]
Square root of array elements:
 [[1.         2.         2.23606798]
 [1.41421356 2.44948974 2.82842712]]


## Saving and loading Numpy arrays

numpy.load() function return the input array from a disk file with npy extension(.npy)

numpy.save() function is used to store the input array in a disk file with npy extension(.npy)

In [0]:
import numpy as np

# cretaing an numpy array
a = np.array(([i for i in range(0,20,2)]))
print("Aray created and which is been saved in new file:")
print(a)

# saving the array in testing.npy file
np.save("testing.npy",a)

# loading the array from testimg.npy to new array
b = np.load("testing.npy")

print("\nArray loaded from the file created:")
print(b)

Aray created and which is been saved in new file:
[ 0  2  4  6  8 10 12 14 16 18]

Array loaded from the file created:
[ 0  2  4  6  8 10 12 14 16 18]


## Slicing ,indexing and manipulation



In [0]:
# basic slicing

import numpy as np 

a = np.arange(20) 
print("Array is:\n",a) 
  
# a[start:stop:step] 
# negative index is taken from the end of the array
print("\n a[-8:17:1]  = ",a[-8:17:1])  
  
# the : operator means all elements till the end 
print("\n last 10 elements",a[10:]) 

Array is:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 a[-8:17:1]  =  [12 13 14 15 16]

 last 10 elements [10 11 12 13 14 15 16 17 18 19]


In [0]:
# boolean indexing
import numpy as np

a = np.arange(20) 
print("Array is:\n",a) 

print("elements whose value is greater than 10:",a[a>10])

Array is:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
elements whose value is greater than 10: [11 12 13 14 15 16 17 18 19]


In [0]:
# advanced indexing
import numpy as np

a = np.array([[1,7,89,1,6],[1,4,5,6,4],[3,6,4,2,6]])
print("Array is:\n",a)

print("Elements at location (0,0),(1,1),(2,2)\n",a[[0,1,2],[0,1,2]]) 


Array is:
 [[ 1  7 89  1  6]
 [ 1  4  5  6  4]
 [ 3  6  4  2  6]]
Elements at location (0,0),(1,1),(2,2)
 [1 4 4]


In [42]:
# NumPy also provides a reshape function to resize an array
import numpy as np

a = np.array([[1,3,2],[3,6,7]])
print("dimensions of a\n",a.shape)

# resizing an array
# even after resizing the size of array should remain same
b = a.reshape(6,1)
print("b:\n",b)

c=np.array([[3,6,7],[12,6,5]])
# Concating two arrays
d=np.concatenate((a,c))
print("concated array\n",d)

# appending elements
print("After appending\n",np.append(a,[1,2,3]))

# deleting object [1,2,3]
print("\n",np.delete(a,[1,2,3]))

dimensions of a
 (2, 3)
b:
 [[1]
 [3]
 [2]
 [3]
 [6]
 [7]]
concated array
 [[ 1  3  2]
 [ 3  6  7]
 [ 3  6  7]
 [12  6  5]]
After appending
 [1 3 2 3 6 7 1 2 3]

 [1 6 7]
